name: Fetch latest Bun release
on:
  workflow_dispatch:
  schedule:
  # no reason, I just want to avoid midnight
    - cron: "05 01 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch latest Bun release
      id: fetch-release
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/oven-sh/bun/releases | jq '.[0].tag_name' --raw-output > bumper
        
        echo "{LATEST_BUN_RELEASE}={$(cat bumper)}" >> $GITHUB_OUTPUT
    - name: Commit results
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        fetch: false
        message: Update to release ${{ steps.fetch-release.outputs.LATEST_BUN_RELEASE }}
        ${{steps.generate_qmkpid.outputs.output}}
        add: "bumper --force"